project_id = "dwtdcpevecugfqncmfvp"

[functions.validate-email-domain]
verify_jwt = false

[functions.approve-user]
verify_jwt = false

[functions.process-sop]
verify_jwt = false

[functions.generate-script-rag]
verify_jwt = false
